import styles from './../styles/index.module.css';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Homework #21 - Next.js 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.wrapper}>
        <h1> Avatar app with Next.js </h1>
        <div className={styles.container}>
          <Link className={styles.link} href={'/ssg'}>
            SSG
          </Link>
          <Link className={styles.link} href={'/ssr'}>
            SSR
          </Link>
        </div>
      </main>
    </>
  );
}
