export const ACTION_TYPES = {
  SET_TODOS: 'SET_TODOS',
  ADD_NEWTODO: 'ADD_NEWTODO',
  DELETE_TODO: 'DELETE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  TOGGLE_COMPLETED: 'TOGGLE_COMPLETED',
  DELETE_COMPLETED: '  DELETE_COMPLETED',
};
